### ISSUE TITLE
Uncertainty intervals not returned from `logquad5q0`

### ISSUE THREAD

**Issue by taylorokonek** [verhulsta/logquad5q0#1]
It seems like since `check = 0` internally in the `lagrange5q0` function, uncertainty intervals are not returned by default at the moment, which is inconsistent with the function documentation

**Comment by taylorokonek** [comment]
Here's a reproducible example:

`input_p2 <- logquad5q0::format_data(
  lower_age = c(0,0),
  upper_age = c(28,365.25*5),
  rate      = c(0.05277284, 0.1394108),
  type      = c("qx", "qx"),
  sex       = c("total", "total"))
lagrange5q0(data = input_p2)`

**Comment by verhulsta** [comment]
Hi, 

Thank you for using the package. You are right and this is a current limitation of the model. Confident intervals are provided only in the two case scenarios given in the README (and described in the associated paper pp 338-39). I have now made clear that this is for these two cases only. Typically, in the example you give, when matching two entry points, there are no degrees of freedom to have fitting uncertainty on k. My colleague Julio Romero Prieto is working a on Bayesian version of the model that should fix this issue eventually.

Best,

**Comment by taylorokonek** [comment]
Thank you for the quick response! This makes sense, and thank you for updating the README to clarify
